
project_id = "ntgrokpnwizohtfkcfec"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.support-assistant]
verify_jwt = false

[functions.ticket-classification]
verify_jwt = false

[functions.first-response-generator]
verify_jwt = false

[functions.feedback-summarizer]
verify_jwt = false

[functions.strategy-gap-analysis]
verify_jwt = false

[functions.page-validator]
verify_jwt = true

