
project_id = "ntgrokpnwizohtfkcfec"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.first-response-generator]
[functions.feedback-summarizer]
[functions.user-insights]
[functions.submission-enhancement]
[functions.ticket-classification]
[functions.reviewer-matching]
[functions.proposal-scoring]
[functions.semantic-search]
[functions.innovation-insights]
[functions.regulatory-analysis]
[functions.learning-recommendations]
[functions.policy-analysis-qa]
[functions.healthcare-policy-analysis]
[functions.vision-2030-alignment]
[functions.policy-impact-simulation]
[functions.investment-match]
[functions.market-analysis]
[functions.support-assistant]
[functions.story-analyzer]
