
import { Innovation } from "@/types/innovations";

export const mockMarketplaceInnovations: Innovation[] = [
  {
    id: "1",
    title: "AI-Powered Diabetes Monitoring System",
    description: "An innovative solution that combines continuous glucose monitoring with AI to predict blood sugar fluctuations and recommend preventive actions.",
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=500&auto=format&fit=crop&q=60",
    category: "Digital Health",
    tags: ["Artificial Intelligence", "Diabetes Care", "Remote Monitoring", "Preventive Health"],
    rating: 4.8,
    status: "Validated",
    createdAt: "2023-05-15T09:24:00Z",
    organization: "MedTech Innovations Ltd",
    website: "https://example.com/diabetes-ai",
    contact: "contact@medtechinnovations.com",
    ipStatus: "patent_granted",
    licensingStatus: "available",
    trl: 8
  },
  {
    id: "2",
    title: "Portable Ultrasound Device",
    description: "A handheld ultrasound device that connects to smartphones for immediate diagnosis in remote or resource-limited settings.",
    imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=60",
    category: "MedTech",
    tags: ["Ultrasound", "Portable Diagnostics", "Remote Healthcare", "Mobile Health"],
    rating: 4.7,
    status: "Scaling",
    createdAt: "2023-06-20T14:35:00Z",
    organization: "Portable Diagnostics Inc.",
    ipStatus: "patent_pending",
    licensingStatus: "exclusive",
    trl: 7
  },
  {
    id: "3",
    title: "Hospital Resource Optimization Platform",
    description: "AI-driven platform that optimizes hospital resource allocation, staff scheduling, and patient flow to maximize efficiency and improve outcomes.",
    imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=60",
    category: "Healthcare IT",
    tags: ["Resource Optimization", "Hospital Management", "AI", "Workflow"],
    rating: 4.5,
    status: "Established",
    createdAt: "2023-03-10T10:12:00Z",
    organization: "HealthFlow Solutions",
    ipStatus: "copyright",
    licensingStatus: "non_exclusive",
    trl: 9
  },
  {
    id: "4",
    title: "Biodegradable Surgical Implants",
    description: "Next-generation biodegradable implants that dissolve safely after fulfilling their function, eliminating the need for removal surgery.",
    imageUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=500&auto=format&fit=crop&q=60",
    category: "MedTech",
    tags: ["Surgical Implants", "Biodegradable", "Materials Science", "Surgery"],
    rating: 4.9,
    status: "Validated",
    createdAt: "2023-07-05T08:45:00Z",
    organization: "BioMaterial Solutions",
    ipStatus: "patent_granted",
    licensingStatus: "available",
    trl: 6
  },
  {
    id: "5",
    title: "Virtual Reality Rehabilitation Platform",
    description: "VR-based rehabilitation platform that gamifies physical therapy exercises, increasing patient engagement and recovery rates.",
    imageUrl: "https://images.unsplash.com/photo-1622979135225-d2ba7f2949d1?w=500&auto=format&fit=crop&q=60",
    category: "Digital Health",
    tags: ["Virtual Reality", "Rehabilitation", "Physical Therapy", "Gamification"],
    rating: 4.6,
    status: "Scaling",
    createdAt: "2023-04-18T16:20:00Z",
    organization: "RehabTech",
    ipStatus: "patent_pending",
    licensingStatus: "negotiating",
    trl: 7
  },
  {
    id: "6",
    title: "Telehealth Platform for Rural Communities",
    description: "Comprehensive telehealth solution designed to work in low-bandwidth environments, bringing quality healthcare to underserved rural communities.",
    imageUrl: "https://images.unsplash.com/photo-1576089172869-4f5f6f315620?w=500&auto=format&fit=crop&q=60",
    category: "Telehealth",
    tags: ["Rural Healthcare", "Telehealth", "Accessibility", "Low-resource Settings"],
    rating: 4.7,
    status: "New",
    createdAt: "2023-08-12T11:30:00Z",
    organization: "Connect Health Access",
    ipStatus: "trade_secret",
    licensingStatus: "available",
    trl: 8
  },
  {
    id: "7",
    title: "AI-Powered Medical Image Analysis",
    description: "Deep learning platform that analyzes medical images to assist in early cancer detection with accuracy exceeding human radiologists.",
    imageUrl: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=500&auto=format&fit=crop&q=60",
    category: "Digital Health",
    tags: ["AI", "Imaging", "Cancer Detection", "Radiology"],
    rating: 4.8,
    status: "Validated",
    createdAt: "2023-02-25T09:15:00Z",
    organization: "MedVision AI",
    ipStatus: "patent_granted",
    licensingStatus: "non_exclusive",
    trl: 8
  },
  {
    id: "8",
    title: "Smart Medication Dispenser",
    description: "IoT-enabled medication dispenser with remote monitoring capabilities, ensuring proper medication adherence for elderly and chronic disease patients.",
    imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=60",
    category: "MedTech",
    tags: ["Medication Adherence", "IoT", "Elderly Care", "Chronic Disease Management"],
    rating: 4.5,
    status: "Scaling",
    createdAt: "2023-09-08T13:45:00Z",
    organization: "Smart Health Devices",
    ipStatus: "patent_pending",
    licensingStatus: "available",
    trl: 9
  }
];
