// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntgrokpnwizohtfkcfec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Z3Jva3Bud2l6b2h0ZmtjZmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzE1MDYsImV4cCI6MjA2MjMwNzUwNn0.8ss2vlY1-BzO9YAmRRPZCe86RmvssyzroRfaa57NjzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);